#!/usr/bin/env python3
"""Export the forms of a running system into JSON the launcher can seed.

What gets written is everything needed to rebuild the forms, not a database
snapshot: UUIDs, timestamps and authorship are dropped and regenerated by the
API at seed time. Workflow nodes reference sections by array index so no UUID
ever leaks in.

Adjust BASE, UID and WANT below to point at the system you are exporting from.
"""
import json, sys, urllib.request, urllib.error, http.cookiejar

BASE = "http://localhost:8080"
UID = "7f89420a-2491-41cc-b2f0-5b6a7bfb6e4e"
ORG = "SDC"
WANT = ["SDC 註冊表單 - 2025", "SDC 註冊表單 - 2026"]

cj = http.cookiejar.CookieJar()
opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))


def call(method, path, body=None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(BASE + path, data=data, method=method)
    req.add_header("Content-Type", "application/json")
    with opener.open(req) as r:
        raw = r.read()
        return json.loads(raw) if raw else None


def clean_choices(choices):
    out = []
    for c in choices or []:
        item = {"name": c.get("name", "")}
        if c.get("isOther"):
            item["isOther"] = True
        if c.get("description"):
            item["description"] = c["description"]
        out.append(item)
    return out


def export_question(q):
    out = {
        "title": q["title"],
        "type": q["type"],
        "required": bool(q.get("required")),
        "description": q.get("description") or {"type": "doc", "content": [{"type": "paragraph"}]},
    }
    ch = clean_choices(q.get("choices"))
    if ch:
        out["choices"] = ch
    # Type-specific settings, only when present.
    for key in ("scale", "uploadFile", "date"):
        if q.get(key):
            out[key] = q[key]
    if q.get("oauthConnect"):
        out["oauthConnect"] = q["oauthConnect"]
    return out


def export_form(meta):
    fid = meta["id"]
    detail = call("GET", f"/api/forms/{fid}")
    sections = call("GET", f"/api/forms/{fid}/sections")
    wf = call("GET", f"/api/forms/{fid}/workflow")["workflow"]

    # GET /sections is not guaranteed to match the flow order, so walk the
    # workflow from START to derive the real section order and export in it.
    nodes = {n["id"]: n for n in wf}
    by_id = {e["section"]["id"]: e for e in sections}

    # Depth-first over the whole graph (true branch first) so the order is
    # stable. The order itself does not affect correctness, since nodes refer to
    # each other by index, but a stable one keeps re-export diffs limited to
    # genuine content changes.
    order, seen = [], set()

    def visit(nid):
        while nid and nid not in seen:
            seen.add(nid)
            n = nodes.get(nid)
            if n is None or n["type"] == "END":
                return
            if n["type"] == "SECTION":
                order.append(nid)
            if n["type"] == "CONDITION":
                visit(n.get("nextTrue"))
                nid = n.get("nextFalse")
                continue
            nid = n.get("next")

    visit(next(n["id"] for n in wf if n["type"] == "START"))

    # Keep sections the graph never reaches, sorted by title for stability.
    orphans = sorted(
        (e["section"]["id"] for e in sections if e["section"]["id"] not in seen),
        key=lambda sid: by_id[sid]["section"]["title"],
    )
    order.extend(orphans)

    idx = {sid: i for i, sid in enumerate(order)}

    out_sections = []
    qidx = {}  # question id -> (section index, question index)
    for i, sid in enumerate(order):
        e = by_id[sid]
        qs = e.get("questions") or []
        for j, q in enumerate(qs):
            qidx[q["id"]] = (i, j)
        out_sections.append({
            "title": e["section"]["title"],
            "description": e["section"].get("description")
            or {"type": "doc", "content": [{"type": "paragraph"}]},
            "questions": [export_question(q) for q in qs],
        })

    # Choice id -> (section, question, choice), used by condition patterns.
    choice_pos = {}
    for i, sid in enumerate(order):
        for j, q in enumerate(by_id[sid].get("questions") or []):
            for k, c in enumerate(q.get("choices") or []):
                choice_pos[c["id"]] = (i, j, k)

    out_nodes = []
    node_index = {}
    for n in wf:
        node_index[n["id"]] = len(out_nodes)
        item = {"type": n["type"], "payload": n.get("payload") or {"x": 0, "y": 0}}
        # Condition labels are generated by the backend and embed the choice
        # UUID of the system they came from. Dropping them keeps the export free
        # of UUIDs; the backend regenerates the label on seed anyway.
        if n["type"] != "CONDITION":
            item["label"] = n["label"]
        if n["type"] == "SECTION":
            item["section"] = idx[n["id"]]
        if n.get("conditionRule"):
            r = n["conditionRule"]
            item["condition"] = {"source": r["source"]}
            if r.get("question") in qidx:
                s, q = qidx[r["question"]]
                item["condition"]["question"] = {"section": s, "question": q}
            # A CHOICE pattern is ^<choice uuid>$; rewrite it as a positional ref.
            pat = r.get("pattern", "")
            cid = pat[1:-1] if pat.startswith("^") and pat.endswith("$") else ""
            if cid in choice_pos:
                s, q, c = choice_pos[cid]
                item["condition"]["choice"] = {"section": s, "question": q, "choice": c}
            else:
                item["condition"]["pattern"] = pat
        out_nodes.append(item)

    for n in wf:
        item = out_nodes[node_index[n["id"]]]
        for key in ("next", "nextTrue", "nextFalse"):
            if n.get(key) in node_index:
                item[key] = node_index[n[key]]

    return {
        "title": detail["title"],
        "previewMessage": detail.get("previewMessage", ""),
        "description": detail.get("description") or {"type": "doc", "content": [{"type": "paragraph"}]},
        "messageAfterSubmission": detail.get("messageAfterSubmission", ""),
        "visibility": detail.get("visibility", "PUBLIC"),
        "sections": out_sections,
        "workflow": out_nodes,
    }


def main():
    call("POST", "/api/auth/login/internal", {"uid": UID})
    forms = call("GET", f"/api/orgs/{ORG}/forms")
    picked = [f for f in forms if f["title"] in WANT]
    if len(picked) != len(WANT):
        print("Some requested forms were not found. Available:", [f["title"] for f in forms], file=sys.stderr)
        sys.exit(1)
    picked.sort(key=lambda f: f["title"])

    out = []
    for meta in picked:
        data = export_form(meta)
        nq = sum(len(s["questions"]) for s in data["sections"])
        print(f"  {data['title']}: {len(data['sections'])} sections / "
              f"{nq} questions / {len(data['workflow'])} nodes")
        out.append(data)

    with open("seed-forms.json", "w") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print("→ seed-forms.json")


if __name__ == "__main__":
    main()
