// Package docker generates the compose setup and drives docker compose.
package docker

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/NYCU-SDC/core-system-launcher/internal/config"
)

// ProjectName is the compose project name, keeping this stack apart from
// anything else on the user's machine.
const ProjectName = "core-system"

// dockerfileName is the Dockerfile the launcher writes into each build context.
// Deliberately not named Dockerfile so it never shadows the upstream one.
const dockerfileName = "Dockerfile.launcher"

// Compose runs docker compose in the given directory, wired to the terminal.
func Compose(ctx context.Context, deployDir string, args ...string) error {
	full := append([]string{"compose", "-p", ProjectName}, args...)
	cmd := exec.CommandContext(ctx, "docker", full...)
	cmd.Dir = deployDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

// ComposeQuiet is the same but captures the combined output instead.
func ComposeQuiet(ctx context.Context, deployDir string, args ...string) (string, error) {
	full := append([]string{"compose", "-p", ProjectName}, args...)
	cmd := exec.CommandContext(ctx, "docker", full...)
	cmd.Dir = deployDir
	out, err := cmd.CombinedOutput()
	return strings.TrimSpace(string(out)), err
}

// WriteDeployFiles generates compose.yaml, setup.yaml and both Dockerfiles.
//
// srcDir is where the upstream sources live; the compose build contexts point
// at it.
func WriteDeployFiles(cfg *config.Config, deployDir, srcDir string, backendDockerfile, frontendDockerfile []byte) error {
	if err := os.MkdirAll(deployDir, 0o755); err != nil {
		return err
	}

	// The Dockerfiles go inside their own build contexts: compose resolves the
	// dockerfile field relative to the context, and pointing outside it is not
	// reliable.
	if err := os.WriteFile(filepath.Join(srcDir, "backend", dockerfileName), backendDockerfile, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(srcDir, "frontend", dockerfileName), frontendDockerfile, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(deployDir, "setup.yaml"), []byte(setupYAML(cfg)), 0o644); err != nil {
		return err
	}
	// The vite build mode file, which decides what ends up baked into the bundle.
	envPath := filepath.Join(srcDir, "frontend", ".env.launcher")
	if err := os.WriteFile(envPath, []byte(frontendEnv(cfg)), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(deployDir, "compose.yaml"), []byte(composeYAML(cfg, srcDir)), 0o644)
}

func setupYAML(cfg *config.Config) string {
	return fmt.Sprintf(`# Generated by core-system-launcher.
#
# The backend reads this on boot to create the initial organization and apply
# member roles. The process is idempotent: an existing org is left alone.
organizations:
  - name: %q
    slug: %q
    description: "Deployed by core-system-launcher"
users:
  - email: %q
    global_role:
      - admin
    org_member:
      - slug: %q
        org_role: admin
    allowed_onboarding: true
`, config.OrgSlug, config.OrgSlug, cfg.AdminEmail, config.OrgSlug)
}

func frontendEnv(cfg *config.Config) string {
	return fmt.Sprintf(`# Generated by core-system-launcher.
#
# VITE_API_BASE_URL only feeds the pnpm dev proxy and never reaches the bundle.
# At runtime the frontend requests relative /api paths through the gateway,
# which is why the frontend and API have to share an origin.
VITE_API_BASE_URL=%s/api

# No analytics for a local deployment.
VITE_GA_ID=

PORT=80
BACKEND_ORIGIN=http://backend:8080
BACKEND_HOST_HEADER=
PUBLIC_ORIGIN=%s
HTML_CACHE_CONTROL=no-store
`, cfg.BaseURL(), cfg.BaseURL())
}

func composeYAML(cfg *config.Config, srcDir string) string {
	// In trial mode the OAuth fields are simply left empty. The backend still
	// starts; only the OAuth login path fails, and the internal login endpoint
	// is used instead.
	return fmt.Sprintf(`# Generated by core-system-launcher. Do not edit by hand.
#
# One port is exposed. The frontend gateway serves the static build and reverse
# proxies /api to the backend. The frontend SDK requests relative paths, so the
# frontend and API must share an origin.
#
#   http://localhost:%d  ->  frontend (gateway)
#                              |- /       -> static build
#                              |- /api/*  -> backend:8080
#                                              |- postgres:5432

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core_system
    ports:
      - "%d:5432"
    volumes:
      # From postgres:18 on, the mount belongs at /var/lib/postgresql.
      # Mounting the old .../data path fails to start.
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12

  backend:
    build:
      context: %s
      dockerfile: %s
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_NAME: core-system-backend
      ENV: launcher
      # DEV switches cookies to SameSite=Lax, no Domain and Secure=false, which
      # is what plain-HTTP localhost needs for them to be accepted.
      DEV: "true"
      # DEBUG additionally exposes POST /api/auth/login/internal.
      DEBUG: "true"
      HOST: "0.0.0.0"
      PORT: "8080"
      # The public entry point; the OAuth redirect URI is derived from it.
      BASE_URL: "%s"
      SECRET: "%s"
      DATABASE_URL: "postgres://postgres:password@postgres:5432/core_system?sslmode=disable"
      MIGRATION_SOURCE: "file:///app/migrations"
      ACCESS_TOKEN_EXPIRATION: "15m"
      REFRESH_TOKEN_EXPIRATION: "720h"
      ALLOW_ORIGINS: "*"
      OTEL_COLLECTOR_URL: ""
      OAUTH_PROXY_BASE_URL: ""
      OAUTH_PROXY_SECRET: ""
      GOOGLE_OAUTH_CLIENT_ID: "%s"
      GOOGLE_OAUTH_CLIENT_SECRET: "%s"
      ALLOW_ONBOARDING_LIST: "%s"
      DEFAULT_GLOBAL_ROLES: "%s:admin"
      DEFAULT_ORG_ROLES: "%s:admin"
      SETUP_PATH: "/app/setup.yaml"
    volumes:
      - ./setup.yaml:/app/setup.yaml:ro

  frontend:
    build:
      context: %s
      dockerfile: %s
      args:
        BUILD_MODE: launcher
    depends_on:
      - backend
    ports:
      - "%d:80"
    environment:
      PORT: "80"
      BACKEND_ORIGIN: "http://backend:8080"
      BACKEND_HOST_HEADER: ""
      PUBLIC_ORIGIN: "%s"
      HTML_CACHE_CONTROL: "no-store"

volumes:
  pgdata:
`,
		cfg.AppPort,
		cfg.PostgresPort,
		filepath.Join(srcDir, "backend"), dockerfileName,
		cfg.BaseURL(), cfg.Secret,
		cfg.GoogleClientID, cfg.GoogleClientSecret,
		cfg.AdminEmail, cfg.AdminEmail, cfg.AdminEmail,
		filepath.Join(srcDir, "frontend"), dockerfileName,
		cfg.AppPort, cfg.BaseURL(),
	)
}
